version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend-volume:
    driver: local
    driver_opts:
      type: none
      device: ./frontend
      o: bind

networks:
  app-network:
    driver: bridge


    